# Generated by Django 5.2.6 on 2025-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
