# Generated by Django 5.2.6 on 2025-09-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_compensation_employee_compensation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='compensation',
            new_name='compensations',
        ),
    ]
