# Generated by Django 5.2.6 on 2025-09-09 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_rename_compensation_employee_compensations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.SmallIntegerField(default=0),
        ),
    ]
